"""Public API facade."""

from principle_viz.api.facade import (
    analyze_common_resource,
    analyze_externality,
    analyze_loanable_funds,
    analyze_minimum_wage,
    analyze_ppf,
    analyze_ppf_growth,
    analyze_public_good,
    analyze_trade,
    build_dwl_report,
    build_tax_visual_guide,
    comparative_statics,
    compare_linear_ppfs,
    compare_subsidy_scenario,
    compare_tax_scenario,
    compute_arc_elasticity,
    compute_point_elasticity,
    compute_surplus,
    elasticity_revenue_schedule,
    evaluate_price_control,
    line_from_inverse,
    line_from_standard,
    solve_discrete_market,
    solve_equilibrium,
    solve_subsidy_equilibrium,
    solve_tax_equilibrium,
)

__all__ = [
    "analyze_common_resource",
    "analyze_externality",
    "analyze_loanable_funds",
    "analyze_minimum_wage",
    "analyze_ppf",
    "analyze_ppf_growth",
    "analyze_public_good",
    "analyze_trade",
    "build_dwl_report",
    "build_tax_visual_guide",
    "comparative_statics",
    "compare_linear_ppfs",
    "compare_subsidy_scenario",
    "compare_tax_scenario",
    "compute_arc_elasticity",
    "compute_point_elasticity",
    "compute_surplus",
    "elasticity_revenue_schedule",
    "evaluate_price_control",
    "line_from_inverse",
    "line_from_standard",
    "solve_discrete_market",
    "solve_equilibrium",
    "solve_subsidy_equilibrium",
    "solve_tax_equilibrium",
]
