"""Principle-Econ public package interface."""

from principle_viz.api import (
    analyze_common_resource,
    analyze_externality,
    analyze_loanable_funds,
    analyze_minimum_wage,
    analyze_ppf,
    analyze_ppf_growth,
    analyze_public_good,
    analyze_trade,
    build_dwl_report,
    build_tax_visual_guide,
    comparative_statics,
    compare_linear_ppfs,
    compare_subsidy_scenario,
    compare_tax_scenario,
    compute_arc_elasticity,
    compute_point_elasticity,
    compute_surplus,
    elasticity_revenue_schedule,
    evaluate_price_control,
    line_from_inverse,
    line_from_standard,
    solve_discrete_market,
    solve_equilibrium,
    solve_subsidy_equilibrium,
    solve_tax_equilibrium,
)
from principle_viz.core.discrete import (
    DiscreteDemand,
    DiscreteEquilibriumResult,
    DiscreteMarketError,
    DiscreteSupply,
    EquilibriumPriceRule,
    solve_discrete_equilibrium,
)
from principle_viz.core.factor_markets import (
    LoanableFundsResult,
    LoanableFundsScenario,
    MinimumWageResult,
)
from principle_viz.core.ppf import (
    ComparativeAdvantageResult,
    PointStatus,
    PPFAnalysisResult,
    PPFError,
    PPFGrowthResult,
    PPFGrowthScenario,
    PPFPoint,
    ProductionPossibilitiesFrontier,
)
from principle_viz.core.public_goods import (
    IndividualBenefit,
    PublicGoodPoint,
    PublicGoodResult,
)
from principle_viz.core.revenue import ElasticityRevenueResult, RevenuePoint
from principle_viz.plot import (
    BUILTIN_COLOR_MODELS,
    COLORBLIND_COLOR_MODEL,
    DEFAULT_COLOR_MODEL,
    MONOCHROME_COLOR_MODEL,
    NORD_COLOR_MODEL,
    Canvas,
    ColorModel,
    MarketFigure,
    PlotTheme,
    get_color_model,
    list_color_models,
)
from principle_viz.policy.common_resources import CommonResourceResult
from principle_viz.policy.externality import ExternalityResult, ExternalityScenario
from principle_viz.policy.subsidy import (
    SubsidyComparisonResult,
    SubsidyEquilibriumResult,
    SubsidyScenario,
    SubsidyTo,
)
from principle_viz.policy.trade import (
    QuotaRentRecipient,
    TradeComparisonResult,
    TradeDirection,
    TradeOutcome,
    TradeScenario,
)
from principle_viz.welfare.discrete import (
    DiscreteSurplusResult,
    compute_discrete_surplus,
)

__all__ = [
    "BUILTIN_COLOR_MODELS",
    "COLORBLIND_COLOR_MODEL",
    "DEFAULT_COLOR_MODEL",
    "MONOCHROME_COLOR_MODEL",
    "NORD_COLOR_MODEL",
    "Canvas",
    "ColorModel",
    "CommonResourceResult",
    "ComparativeAdvantageResult",
    "DiscreteDemand",
    "DiscreteEquilibriumResult",
    "DiscreteMarketError",
    "DiscreteSupply",
    "DiscreteSurplusResult",
    "ElasticityRevenueResult",
    "EquilibriumPriceRule",
    "ExternalityResult",
    "ExternalityScenario",
    "IndividualBenefit",
    "LoanableFundsResult",
    "LoanableFundsScenario",
    "MarketFigure",
    "MinimumWageResult",
    "PPFAnalysisResult",
    "PPFError",
    "PPFGrowthResult",
    "PPFGrowthScenario",
    "PPFPoint",
    "PlotTheme",
    "PointStatus",
    "ProductionPossibilitiesFrontier",
    "PublicGoodPoint",
    "PublicGoodResult",
    "QuotaRentRecipient",
    "RevenuePoint",
    "SubsidyComparisonResult",
    "SubsidyEquilibriumResult",
    "SubsidyScenario",
    "SubsidyTo",
    "TradeComparisonResult",
    "TradeDirection",
    "TradeOutcome",
    "TradeScenario",
    "analyze_common_resource",
    "analyze_externality",
    "analyze_loanable_funds",
    "analyze_minimum_wage",
    "analyze_ppf",
    "analyze_ppf_growth",
    "analyze_public_good",
    "analyze_trade",
    "build_dwl_report",
    "build_tax_visual_guide",
    "comparative_statics",
    "compare_linear_ppfs",
    "compare_subsidy_scenario",
    "compare_tax_scenario",
    "compute_arc_elasticity",
    "compute_discrete_surplus",
    "compute_point_elasticity",
    "compute_surplus",
    "elasticity_revenue_schedule",
    "evaluate_price_control",
    "get_color_model",
    "line_from_inverse",
    "line_from_standard",
    "list_color_models",
    "solve_discrete_equilibrium",
    "solve_discrete_market",
    "solve_equilibrium",
    "solve_subsidy_equilibrium",
    "solve_tax_equilibrium",
]
